### ISSUE TITLE
Stuck in "FusionAuth is starting" on 1.19.2 via Docker install

### ISSUE THREAD

**Issue by robjanssen** [FusionAuth/fusionauth-issues#851]
### Description 

I noticed that 1.19 has been released, so I was eager to see what changed.

However, when I open localhost:9011, it seems stuck forever in the FusionAuth is starting-screen. I opened the logs and saw this:

```
===================================================================================================

Unable to start the server. Here's why:

[Error injecting constructor, java.lang.IllegalArgumentException: hosts must not be null nor empty]
         -> [class java.lang.IllegalArgumentException] hosts must not be null nor empty

===================================================================================================

2020-09-07 9:22:26.504 AM ERROR org.primeframework.mvc.guice.GuiceBootstrap - Unable to start the server. Exception:

com.google.inject.CreationException: Unable to create injector, see the following errors:

 1) Error injecting constructor, java.lang.IllegalArgumentException: hosts must not be null nor empty
   at io.fusionauth.api.service.search.ElasticSearchClientProvider.<init>(ElasticSearchClientProvider.java:30)
   at io.fusionauth.api.service.guice.ServiceModule.configure(ServiceModule.java:163) (via modules: io.fusionauth.app.guice.FusionAuthModule -> com.google.inject.util.Modules$OverrideModule -> io.fusionauth.api.guice.APIModule -> io.fusionauth.api.service.guice.ServiceModule)
   while locating io.fusionauth.api.service.search.ElasticSearchClientProvider

 1 error
         at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:554)
         at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:188)
         at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:111)
         at com.google.inject.Guice.createInjector(Guice.java:87)
         at com.google.inject.Guice.createInjector(Guice.java:69)
         at com.google.inject.Guice.createInjector(Guice.java:59)
         at org.primeframework.mvc.guice.GuiceBootstrap.initialize(GuiceBootstrap.java:58)
         at com.inversoft.maintenance.MaintenanceModeService.done(MaintenanceModeService.java:67)
         at com.inversoft.maintenance.MaintenanceModeThreadSafeHelper.areWeDoneYet(MaintenanceModeThreadSafeHelper.java:59)
         at com.inversoft.maintenance.action.MaintenanceModeDoneAction.lambda$get$0(MaintenanceModeDoneAction.java:52)
         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
         at java.base/java.lang.Thread.run(Thread.java:832)
 Caused by: java.lang.IllegalArgumentException: hosts must not be null nor empty
         at org.elasticsearch.client.RestClient.builder(RestClient.java:173)
         at com.inversoft.search.ElasticRestClientHelper.buildClient(ElasticRestClientHelper.java:73)
         at io.fusionauth.api.service.search.ElasticSearchClientProvider.<init>(ElasticSearchClientProvider.java:32)
         at io.fusionauth.api.service.search.ElasticSearchClientProvider$$FastClassByGuice$$d7116b9a.newInstance(<generated>)
         at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
         at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
         at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
         at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
         at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
         at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
         at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
         at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
         at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
```

It seems like the app is assuming there should be an ElasticSearch host specified, even though I didn't want to use ElasticSearch.

### Affects versions
1.19.2

### Steps to reproduce

1. follow the the instructions at https://fusionauth.io/docs/v1/tech/installation-guide/docker that explain how to install it without ElasticSearch
```
curl -o docker-compose.yml https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/docker-compose.yml
curl -o .env https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/.env
docker-compose up
```

### Expected behavior
FusionAuth should start up without any errors and present the setup wizard screen.

### Screenshots
N/A

### Platform
- Device: Desktop
- OS: Windows 10 Pro, 64-bit running Docker Desktop 2.3.0.4
- Browser: Chrome 85.0.4.
- Database: PostgreSQL (as supplied in the Docker image)

### Additional context
I managed to work around the issue as follows: when I check the `fusionauth.properties file`, the `search.servers` line was commented out. By uncommenting that line it looks like everything is working locally as intended - I get the setup screen and everything!

```
# Specify the location of your FusionAuth Search servers. Multiple values may be specified using a comma separator.     
# This configuration is used by FusionAuth App to connect to the ElasticSearch nodes. The specified port should be the  
# configured value for 'fusionauth-search.http-port'.                                                                   
#                                                                                                                       
# Single host example: http://localhost:9021                                                                            
# Multiple hosts example: http://localhost:9021,http://192.168.1.42:9021
search.servers=http://localhost:9021 # this line was originally commented out
```

Hope this helps!

**Comment by robotdan** [comment]
Thanks the issue @robjanssen , in theory we fixed this in 1.19.1. We'll try to recreate.

**Comment by robotdan** [comment]
@robjanssen can you still recreate this on the latest version of FusionAuth?

**Comment by robjanssen** [comment]
@robotdan The latest at the moment of writing is 1.19.6. All conditions are identical to those already mentioned.

I'm sorry to say that the problem still persists :(

[complete_log.txt](https://github.com/FusionAuth/fusionauth-issues/files/5260607/complete_log.txt)

I've attached the complete log file - perhaps it helps.

**Comment by robotdan** [comment]
The startup log looks like it is still using `1.19.0`. 

Can you try running this `docker pull fusionauth/fusionauth-app:latest`  and then run the `docker-compose up` again? 

The `docker-compose` script uses the `:latest` tag, but Docker doesn't dynamically pull the `:latest` tag, it is a point in time pull.

**Comment by robjanssen** [comment]
> The startup log looks like it is still using `1.19.0`.
> 
> Can you try running this `docker pull fusionauth/fusionauth-app:latest` and then run the `docker-compose up` again?
> 
> The `docker-compose` script uses the `:latest` tag, but Docker doesn't dynamically pull the `:latest` tag, it is a point in time pull.

I did - and now it works! Thank you so much for your advice 😄
